/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["presign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{logId}/items/{itemId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{logId}/items/{itemId}/hashtags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addHashtag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getList"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/{itineraryId}/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addDay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/{itineraryId}/days/{dayId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/group/{groupId}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateItinerary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/kakao/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["kakaoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/migration/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/api/logs/{logId}/items/{itemId}/photos/{photoId}/representative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["setRepresentative"];
        trace?: never;
    };
    "/api/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDetail"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["update"];
        trace?: never;
    };
    "/api/itineraries/{itineraryId}/days/{dayId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        patch: operations["updateItem"];
        trace?: never;
    };
    "/api/itineraries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put?: never;
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch: operations["update_1"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transit/arrival/bus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBusArrival"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spots/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/spot/{spotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLogsBySpot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{groupId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["myGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{spotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDetail_1"];
        put?: never;
        post?: never;
        delete: operations["cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{logId}/items/{itemId}/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{logId}/items/{itemId}/hashtags/{hashtagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteHashtag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/{itineraryId}/days/{dayId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteDay"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VisitRequest: {
            /** Format: uuid */
            tourSpotId: string;
            /** Format: double */
            gpsLat: number;
            /** Format: double */
            gpsLng: number;
        };
        ApiResponseVisitResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["VisitResponse"];
        };
        VisitResponse: {
            /** Format: uuid */
            visitId?: string;
            verified?: boolean;
            /** Format: double */
            distanceMeters?: number;
        };
        PresignUploadRequest: {
            contentType: string;
        };
        ApiResponsePresignUploadResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PresignUploadResponse"];
        };
        PresignUploadResponse: {
            uploadUrl?: string;
            publicUrl?: string;
        };
        CreateLogRequest: {
            /** Format: uuid */
            itineraryId: string;
            isPublic?: boolean;
        };
        ApiResponseTravelLogDetailResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelLogDetailResponse"];
        };
        TravelLogDayResponse: {
            /** Format: int32 */
            dayNumber?: number;
            /** Format: date */
            date?: string;
            items?: components["schemas"]["TravelLogItemResponse"][];
        };
        TravelLogDetailResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            itineraryId?: string;
            title?: string;
            /** Format: int32 */
            totalSpots?: number;
            duration?: string;
            /** Format: date */
            startDate?: string;
            isPublic?: boolean;
            thumbnailPhotoUrl?: string;
            /** Format: date-time */
            createdAt?: string;
            days?: components["schemas"]["TravelLogDayResponse"][];
        };
        TravelLogHashtagResponse: {
            /** Format: uuid */
            id?: string;
            tag?: string;
        };
        TravelLogItemResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            itineraryItemId?: string;
            spotName?: string;
            arrivalTime?: string;
            /** Format: int32 */
            orderIndex?: number;
            photos?: components["schemas"]["TravelLogPhotoResponse"][];
            hashtags?: components["schemas"]["TravelLogHashtagResponse"][];
        };
        TravelLogPhotoResponse: {
            /** Format: uuid */
            id?: string;
            photoUrl?: string;
            representative?: boolean;
        };
        AddPhotoRequest: {
            photoUrl: string;
        };
        ApiResponseTravelLogPhotoResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelLogPhotoResponse"];
        };
        AddHashtagRequest: {
            tag: string;
        };
        ApiResponseTravelLogHashtagResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelLogHashtagResponse"];
        };
        CreateItineraryRequest: {
            planType?: string;
            title?: string;
            /** Format: date */
            startAt?: string;
            /** Format: date */
            endAt?: string;
            /** Format: uuid */
            groupId?: string;
        };
        ApiResponseItineraryDetailResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ItineraryDetailResponse"];
        };
        ItineraryDayResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            dayNumber?: number;
            /** Format: date */
            date?: string;
            items?: components["schemas"]["ItineraryItemResponse"][];
        };
        ItineraryDetailResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            sessionId?: string;
            /** Format: uuid */
            groupId?: string;
            title?: string;
            planType?: string;
            status?: string;
            /** Format: date */
            startAt?: string;
            /** Format: date */
            endAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            days?: components["schemas"]["ItineraryDayResponse"][];
        };
        ItineraryItemResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            orderIndex?: number;
            spot?: components["schemas"]["SpotSummary"];
            arrivalTime?: string;
            /** Format: int32 */
            durationMin?: number;
            travelMode?: string;
            /** Format: int32 */
            travelTimeMin?: number;
            memo?: string;
        };
        SpotSummary: {
            /** Format: uuid */
            id?: string;
            name?: string;
            category?: string;
            address?: string;
            lat?: number;
            lng?: number;
            thumbnailUrl?: string;
            isCollected?: boolean;
        };
        AddDayRequest: {
            /** Format: int32 */
            dayNumber: number;
            /** Format: date */
            date?: string;
        };
        ApiResponseItineraryDayResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ItineraryDayResponse"];
        };
        AddItemRequest: {
            /** Format: uuid */
            spotId: string;
            /** Format: int32 */
            orderIndex?: number;
            arrivalTime?: string;
            /** Format: int32 */
            durationMin?: number;
            travelMode?: string;
            /** Format: int32 */
            travelTimeMin?: number;
            memo?: string;
        };
        ApiResponseItineraryItemResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ItineraryItemResponse"];
        };
        GroupItineraryRequest: {
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            optimizationType?: string;
        };
        ApiResponseItineraryGenerateResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ItineraryGenerateResponse"];
        };
        DayPlan: {
            /** Format: int32 */
            day?: number;
            spots?: components["schemas"]["SpotInfo"][];
            routes?: components["schemas"]["TransitRouteResponse"][];
        };
        ItineraryGenerateResponse: {
            planA?: components["schemas"]["PlanOption"];
            planB?: components["schemas"]["PlanOption"];
            planC?: components["schemas"]["PlanOption"];
        };
        PlanOption: {
            type?: string;
            label?: string;
            description?: string;
            days?: components["schemas"]["DayPlan"][];
        };
        SpotInfo: {
            contentId?: string;
            name?: string;
            category?: string;
            sigungu?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            address?: string;
            thumbnailUrl?: string;
            operatingHours?: string;
        };
        SubPath: {
            type?: string;
            /** Format: int32 */
            sectionTime?: number;
            routeNo?: string;
            /** Format: int32 */
            stationCount?: number;
            startName?: string;
            endName?: string;
            /** Format: double */
            startX?: number;
            /** Format: double */
            startY?: number;
            /** Format: double */
            endX?: number;
            /** Format: double */
            endY?: number;
            startArsId?: string;
            /** Format: int32 */
            startId?: number;
            /** Format: int32 */
            wayCode?: number;
            /** Format: int32 */
            remainMinutes?: number;
        };
        TransitOption: {
            type?: string;
            /** Format: int32 */
            totalTime?: number;
            /** Format: int32 */
            totalFare?: number;
            /** Format: int32 */
            transferCount?: number;
            estimated?: boolean;
            subPaths?: components["schemas"]["SubPath"][];
        };
        TransitRouteResponse: {
            options?: components["schemas"]["TransitOption"][];
        };
        SwipeItem: {
            contentId?: string;
            liked?: boolean;
        };
        SwipeRequest: {
            swipes: components["schemas"]["SwipeItem"][];
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            optimizationType?: string;
        };
        CreateGroupRequest: {
            name?: string;
        };
        ApiResponseGroupResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GroupResponse"];
        };
        GroupResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            inviteCode?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        JoinGroupRequest: {
            inviteCode: string;
        };
        ApiResponseTokenResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TokenResponse"];
        };
        TokenResponse: {
            accessToken?: string;
            tokenType?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
        };
        ApiResponseKakaoLoginResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["KakaoLoginResponse"];
        };
        KakaoLoginResponse: {
            accessToken?: string;
            tokenType?: string;
            isNewUser?: boolean;
        };
        MigrationResult: {
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            saved?: number;
            /** Format: int32 */
            updated?: number;
            /** Format: int32 */
            failed?: number;
        };
        UpdateProfileRequest: {
            nickname?: string;
            profileImageUrl?: string;
        };
        ApiResponseUserProfileResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["UserProfileResponse"];
        };
        UserProfileResponse: {
            /** Format: uuid */
            id?: string;
            nickname?: string;
            profileImageUrl?: string;
            email?: string;
        };
        UpdateLogRequest: {
            isPublic?: boolean;
        };
        UpdateItemRequest: {
            /** Format: int32 */
            orderIndex?: number;
            arrivalTime?: string;
            /** Format: int32 */
            durationMin?: number;
            travelMode?: string;
            /** Format: int32 */
            travelTimeMin?: number;
            memo?: string;
        };
        UpdateItineraryRequest: {
            title?: string;
            /** Format: date */
            startAt?: string;
            /** Format: date */
            endAt?: string;
            status?: string;
        };
        ApiResponseString: {
            success?: boolean;
            message?: string;
            data?: string;
        };
        ApiResponseInteger: {
            success?: boolean;
            message?: string;
            /** Format: int32 */
            data?: number;
        };
        SpotSearchResponse: {
            /** Format: uuid */
            spotId?: string;
            name?: string;
            category?: string;
            /** Format: int32 */
            sigunguId?: number;
            sigunguName?: string;
            address?: string;
            thumbnailUrl?: string;
            isCollection?: boolean;
            collected?: boolean;
        };
        ApiResponseListTravelLogSummaryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelLogSummaryResponse"][];
        };
        TravelLogSummaryResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            thumbnailPhotoUrl?: string;
            isPublic?: boolean;
            /** Format: date */
            startDate?: string;
            /** Format: int32 */
            totalSpots?: number;
            authorNickname?: string;
            /** Format: int32 */
            addedCount?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseListItinerarySummaryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ItinerarySummaryResponse"][];
        };
        ItinerarySummaryResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            planType?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseListGroupMemberResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GroupMemberResponse"][];
        };
        GroupMemberResponse: {
            /** Format: uuid */
            userId?: string;
            nickname?: string;
            /** Format: date-time */
            joinedAt?: string;
        };
        ApiResponseListGroupResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GroupResponse"][];
        };
        CollectionListResponse: {
            /** Format: uuid */
            spotId?: string;
            name?: string;
            /** Format: int32 */
            sigunguId?: number;
            thumbnailUrl?: string;
            collected?: boolean;
            /** Format: date-time */
            collectedAt?: string;
        };
        CollectionDetailResponse: {
            /** Format: uuid */
            spotId?: string;
            collected?: boolean;
            /** Format: date-time */
            collectedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVisitResponse"];
                };
            };
        };
    };
    presign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignUploadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePresignUploadResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLogRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogDetailResponse"];
                };
            };
        };
    };
    addPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPhotoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogPhotoResponse"];
                };
            };
        };
    };
    addHashtag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddHashtagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogHashtagResponse"];
                };
            };
        };
    };
    getList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListItinerarySummaryResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItineraryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryDetailResponse"];
                };
            };
        };
    };
    addDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDayRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryDayResponse"];
                };
            };
        };
    };
    addItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: string;
                dayId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryItemResponse"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupItineraryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryGenerateResponse"];
                };
            };
        };
    };
    generateItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwipeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryGenerateResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupResponse"];
                };
            };
        };
    };
    join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGroupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupResponse"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    kakaoLogin: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseKakaoLoginResponse"];
                };
            };
        };
    };
    run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MigrationResult"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserProfileResponse"];
                };
            };
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserProfileResponse"];
                };
            };
        };
    };
    setRepresentative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logId: string;
                itemId: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogPhotoResponse"];
                };
            };
        };
    };
    getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogDetailResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLogRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogDetailResponse"];
                };
            };
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: string;
                dayId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: string;
                dayId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryItemResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryDetailResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItineraryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryDetailResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    getBusArrival: {
        parameters: {
            query: {
                arsId: string;
                routeNo: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInteger"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                keyword?: string;
                sigunguId?: number;
                category?: string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SpotSearchResponse"][];
                };
            };
        };
    };
    getLogsBySpot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelLogSummaryResponse"];
                };
            };
        };
    };
    getPublicLogs: {
        parameters: {
            query?: {
                category?: string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelLogSummaryResponse"];
                };
            };
        };
    };
    getMyLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelLogSummaryResponse"];
                };
            };
        };
    };
    members: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListGroupMemberResponse"];
                };
            };
        };
    };
    myGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListGroupResponse"];
                };
            };
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectionListResponse"][];
                };
            };
        };
    };
    getDetail_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectionDetailResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deletePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logId: string;
                itemId: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteHashtag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logId: string;
                itemId: string;
                hashtagId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: string;
                dayId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
