/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 방문 인증 이력 조회 (담당: 윤제승)
         * @description 로그인한 사용자의 방문 인증 시도 이력을 최신순으로 조회합니다.
         */
        get: operations["getHistory"];
        put?: never;
        /**
         * 방문 인증 (담당: 윤제승)
         * @description 위치 정보를 기반으로 사용자가 해당 장소를 실제 방문했는지 인증합니다.
         */
        post: operations["verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/visits/{visitId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 방문 인증 사진 첨부 (담당: 윤제승)
         * @description GPS 인증에 성공한 방문 기록에 촬영한 사진을 첨부합니다. photoUrl은 /api/uploads/presign으로 S3에 업로드 후 받은 publicUrl을 그대로 사용합니다.
         */
        post: operations["attachPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * S3 업로드용 Presigned URL 발급 (담당: 윤제승)
         * @description 클라이언트가 이미지를 S3에 직접 PUT 업로드할 수 있는 presigned URL을 발급합니다. 응답의 publicUrl을 photoUrl/profileImageUrl 등 기존 필드에 그대로 사용하면 됩니다.
         */
        post: operations["presign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/swipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 스와이프 결과 제출 (담당: 유정)
         * @description 사용자의 스와이프(좋아요/싫어요) 결과를 세션 단위로 저장합니다. groupId를 함께 지정하면 그룹 일정 자동 생성(/api/itineraries/group/{groupId}/generate) 시 취합 대상이 됩니다.
         */
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 여행 기록 생성 (담당: 윤제승)
         * @description 새로운 여행 기록(로그)을 생성합니다.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{logId}/items/{itemId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 사진 추가 (담당: 윤제승)
         * @description 여행 기록의 특정 방문 항목에 사진을 추가합니다.
         */
        post: operations["addPhoto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{logId}/items/{itemId}/hashtags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 해시태그 추가 (담당: 윤제승)
         * @description 여행 기록의 방문 항목에 해시태그를 추가합니다.
         */
        post: operations["addHashtag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 일정 목록 조회 (담당: 윤제승)
         * @description 로그인한 사용자가 만든 일정 목록을 요약 정보로 조회합니다.
         */
        get: operations["getList"];
        put?: never;
        /**
         * 일정 생성 (담당: 윤제승)
         * @description 새로운 여행 일정을 생성합니다.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/{itineraryId}/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 일차 추가 (담당: 윤제승)
         * @description 일정에 새로운 여행 일차(Day)를 추가합니다.
         */
        post: operations["addDay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/{itineraryId}/days/{dayId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 방문 항목 추가 (담당: 윤제승)
         * @description 특정 일차에 방문할 장소(항목)를 추가합니다.
         */
        post: operations["addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/vote-sessions/{sessionId}/votes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 투표 참여 (담당: 유정)
         * @description A/B/C안 중 하나에 투표합니다.
         */
        post: operations["castVote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/vote-sessions/{sessionId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 일정 확정 (리더 전용) (담당: 유정)
         * @description 투표 결과 최다득표안을 확정합니다. 동률이면 selectedPlan을 지정해야 합니다. freePass=true면 투표 결과와 무관하게 selectedPlan으로 즉시 확정합니다.
         */
        post: operations["finalize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/group/{groupId}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 그룹 일정 자동 생성 (담당: 유정)
         * @description 그룹 멤버들의 스와이프 결과를 종합하여 그룹 일정을 자동 생성합니다.
         */
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 일정 자동 생성 (담당: 유정)
         * @description 사용자의 스와이프(좋아요/싫어요) 결과를 기반으로 A/B 2가지 일정 후보를 자동 생성합니다.
         */
        post: operations["generateItinerary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 그룹 생성 (담당: 윤제승)
         * @description 새로운 여행 그룹을 생성합니다.
         */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 그룹 참여 (담당: 윤제승)
         * @description 초대 코드를 이용해 기존 그룹에 참여합니다.
         */
        post: operations["join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks/{spotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 북마크 추가 (담당: 윤제승)
         * @description 관광지를 북마크에 추가합니다.
         */
        post: operations["addBookmark"];
        /**
         * 북마크 삭제 (담당: 윤제승)
         * @description 관광지에 대한 북마크를 삭제합니다.
         */
        delete: operations["removeBookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Access Token 재발급 (담당: 성빈)
         * @description 쿠키에 저장된 Refresh Token을 검증하여 새로운 Access Token을 발급합니다.
         */
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃 (담당: 성빈)
         * @description Redis에 저장된 Refresh Token을 삭제하고 쿠키를 만료시킵니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/kakao/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 카카오 로그인 (담당: 성빈)
         * @description 카카오 인가 코드로 액세스 토큰과 사용자 정보를 받아 회원가입/로그인을 처리하고 서비스 자체 토큰을 발급합니다.
         */
        post: operations["kakaoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/migration/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** (담당: 유정) */
        post: operations["run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 프로필 조회 (담당: 윤제승)
         * @description 로그인한 사용자의 프로필 정보를 조회합니다.
         */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 내 프로필 수정 (담당: 윤제승)
         * @description 로그인한 사용자의 닉네임, 프로필 이미지 등 프로필 정보를 수정합니다.
         */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/api/logs/{logId}/items/{itemId}/photos/{photoId}/representative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 대표 사진 설정 (담당: 윤제승)
         * @description 방문 항목에 포함된 사진 중 하나를 대표 사진으로 지정합니다.
         */
        patch: operations["setRepresentative"];
        trace?: never;
    };
    "/api/logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 여행 기록 상세 조회 (담당: 윤제승)
         * @description 여행 기록 ID로 사진, 해시태그를 포함한 상세 정보를 조회합니다.
         */
        get: operations["getDetail"];
        put?: never;
        post?: never;
        /**
         * 여행 기록 삭제 (담당: 윤제승)
         * @description 여행 기록을 삭제합니다.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /**
         * 여행 기록 수정 (담당: 윤제승)
         * @description 여행 기록의 내용을 수정합니다.
         */
        patch: operations["update"];
        trace?: never;
    };
    "/api/itineraries/{itineraryId}/days/{dayId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 방문 항목 삭제 (담당: 윤제승)
         * @description 일차에서 특정 방문 항목을 삭제합니다.
         */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        /**
         * 방문 항목 수정 (담당: 윤제승)
         * @description 일차에 속한 방문 항목의 시간, 순서 등 정보를 수정합니다.
         */
        patch: operations["updateItem"];
        trace?: never;
    };
    "/api/itineraries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 일정 상세 조회 (담당: 윤제승)
         * @description 일정 ID로 일차 및 방문 항목을 포함한 일정 상세 정보를 조회합니다.
         */
        get: operations["getById"];
        put?: never;
        post?: never;
        /**
         * 일정 삭제 (담당: 윤제승)
         * @description 일정을 삭제합니다.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        /**
         * 일정 수정 (담당: 윤제승)
         * @description 일정의 제목, 기간 등 기본 정보를 수정합니다.
         */
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/itineraries/days/{dayId}/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 일정 최적화 (담당: 유정)
         * @description 좌표 기반 동선 재정렬 + 운영시간 반영
         */
        patch: operations["optimize"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 서버 상태 확인 (담당: 유정)
         * @description 서버가 정상적으로 동작 중인지 확인합니다.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transit/arrival/bus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 버스 실시간 도착정보 조회 (담당: 유정)
         * @description 정류소 ID와 노선번호로 버스의 실시간 도착 예정시간(분)을 조회합니다. 프론트엔드 폴링용 API입니다.
         */
        get: operations["getBusArrival"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spots/{spotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관광지 상세 조회 (담당: 유정)
         * @description spotId로 관광지 상세 정보(DB 기본정보 + TourAPI 개요/이미지)를 조회합니다.
         */
        get: operations["getDetail_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spots/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 관광지 검색 (담당: 유정)
         * @description 키워드, 지역(시군구), 카테고리, 정렬 기준으로 관광지를 검색합니다.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/spot/{spotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 여행지별 기록 조회 (담당: 윤제승)
         * @description 특정 여행지(스팟)에 대한 여행 기록 목록을 조회합니다.
         */
        get: operations["getLogsBySpot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 공개 여행 기록 목록 조회 (담당: 윤제승)
         * @description 다른 사용자들에게 공개된 여행 기록을 카테고리, 정렬 기준으로 조회합니다.
         */
        get: operations["getPublicLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 여행 기록 목록 조회 (담당: 윤제승)
         * @description 로그인한 사용자가 작성한 여행 기록 목록을 조회합니다.
         */
        get: operations["getMyLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/vote-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 투표 현황 조회 (담당: 유정) */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{groupId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 그룹 멤버 조회 (담당: 윤제승)
         * @description 특정 그룹에 속한 멤버 목록을 조회합니다.
         */
        get: operations["members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 그룹 목록 조회 (담당: 윤제승)
         * @description 현재 로그인한 사용자가 속한 그룹 목록을 조회합니다.
         */
        get: operations["myGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 찜 목록 조회 (담당: 유정)
         * @description 로그인한 사용자가 찜한 여행지 목록을 조회합니다.
         */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/{spotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 찜 상세 조회 (담당: 유정)
         * @description 찜한 특정 여행지의 상세 정보를 조회합니다.
         */
        get: operations["getDetail_2"];
        put?: never;
        post?: never;
        /**
         * 찜 취소 (담당: 유정)
         * @description 여행지에 대한 찜을 취소합니다.
         */
        delete: operations["cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/collections/swipe-deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 도감 스와이프 덱 조회 (담당: 유정)
         * @description 도감 카테고리(바다/자연/문화/체험)별로 랜덤 관광지 총 10곳을 반환합니다.
         */
        get: operations["getSwipeDeck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 북마크 목록 조회 (담당: 윤제승)
         * @description 로그인한 사용자가 북마크한 관광지 목록을 조회합니다.
         */
        get: operations["getBookmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{logId}/items/{itemId}/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 사진 삭제 (담당: 윤제승)
         * @description 여행 기록의 방문 항목에서 특정 사진을 삭제합니다.
         */
        delete: operations["deletePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{logId}/items/{itemId}/hashtags/{hashtagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 해시태그 삭제 (담당: 윤제승)
         * @description 여행 기록의 방문 항목에서 특정 해시태그를 삭제합니다.
         */
        delete: operations["deleteHashtag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/itineraries/{itineraryId}/days/{dayId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 일차 삭제 (담당: 윤제승)
         * @description 일정에서 특정 일차(Day)를 삭제합니다.
         */
        delete: operations["deleteDay"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VisitRequest: {
            /** Format: uuid */
            tourSpotId: string;
            /** Format: double */
            gpsLat: number;
            /** Format: double */
            gpsLng: number;
        };
        ApiResponseVisitResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["VisitResponse"];
        };
        VisitResponse: {
            /** Format: uuid */
            visitId?: string;
            verified?: boolean;
            /** Format: double */
            distanceMeters?: number;
            firstVisit?: boolean;
        };
        AttachVisitPhotoRequest: {
            photoUrl: string;
        };
        ApiResponseVisitPhotoResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["VisitPhotoResponse"];
        };
        VisitPhotoResponse: {
            /** Format: uuid */
            photoId?: string;
            /** Format: uuid */
            visitId?: string;
            photoUrl?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PresignUploadRequest: {
            contentType: string;
        };
        ApiResponsePresignUploadResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PresignUploadResponse"];
        };
        PresignUploadResponse: {
            uploadUrl?: string;
            publicUrl?: string;
        };
        SwipeItem: {
            contentId?: string;
            liked?: boolean;
        };
        SwipeSubmitRequest: {
            swipes: components["schemas"]["SwipeItem"][];
            /** Format: uuid */
            groupId?: string;
        };
        ApiResponseSwipeSessionResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["SwipeSessionResponse"];
        };
        SwipeSessionResponse: {
            /** Format: uuid */
            sessionId?: string;
            /** Format: uuid */
            groupId?: string;
            status?: string;
            /** Format: int32 */
            resultCount?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateLogRequest: {
            /** Format: uuid */
            itineraryId: string;
            isPublic?: boolean;
            /** Format: int32 */
            mood?: number;
            theme?: string;
        };
        ApiResponseTravelLogDetailResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelLogDetailResponse"];
        };
        GroupMemberResponse: {
            /** Format: uuid */
            userId?: string;
            nickname?: string;
            /** Format: date-time */
            joinedAt?: string;
        };
        TravelLogDayResponse: {
            /** Format: int32 */
            dayNumber?: number;
            /** Format: date */
            date?: string;
            items?: components["schemas"]["TravelLogItemResponse"][];
        };
        TravelLogDetailResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            itineraryId?: string;
            title?: string;
            /** Format: int32 */
            totalSpots?: number;
            /** Format: int32 */
            collectedSpots?: number;
            duration?: string;
            /** Format: date */
            startDate?: string;
            isPublic?: boolean;
            thumbnailPhotoUrl?: string;
            /** Format: int32 */
            mood?: number;
            theme?: string;
            /** Format: int32 */
            travelNumber?: number;
            /** Format: date-time */
            createdAt?: string;
            days?: components["schemas"]["TravelLogDayResponse"][];
            groupMembers?: components["schemas"]["GroupMemberResponse"][];
        };
        TravelLogHashtagResponse: {
            /** Format: uuid */
            id?: string;
            tag?: string;
        };
        TravelLogItemResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            itineraryItemId?: string;
            spotName?: string;
            spotCategory?: string;
            arrivalTime?: string;
            /** Format: int32 */
            orderIndex?: number;
            photos?: components["schemas"]["TravelLogPhotoResponse"][];
            hashtags?: components["schemas"]["TravelLogHashtagResponse"][];
        };
        TravelLogPhotoResponse: {
            /** Format: uuid */
            id?: string;
            photoUrl?: string;
            representative?: boolean;
        };
        AddPhotoRequest: {
            photoUrl: string;
        };
        ApiResponseTravelLogPhotoResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelLogPhotoResponse"];
        };
        AddHashtagRequest: {
            tag: string;
        };
        ApiResponseTravelLogHashtagResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelLogHashtagResponse"];
        };
        CreateItineraryRequest: {
            planType?: string;
            title?: string;
            /** Format: date */
            startAt?: string;
            startTime?: string;
            /** Format: date */
            endAt?: string;
            endTime?: string;
            /** Format: uuid */
            groupId?: string;
            /** Format: uuid */
            sessionId?: string;
        };
        ApiResponseItineraryDetailResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ItineraryDetailResponse"];
        };
        ItineraryDayResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            dayNumber?: number;
            /** Format: date */
            date?: string;
            items?: components["schemas"]["ItineraryItemResponse"][];
        };
        ItineraryDetailResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            sessionId?: string;
            /** Format: uuid */
            groupId?: string;
            title?: string;
            planType?: string;
            status?: string;
            /** Format: date */
            startAt?: string;
            /** Format: date */
            endAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            days?: components["schemas"]["ItineraryDayResponse"][];
        };
        ItineraryItemResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            orderIndex?: number;
            spot?: components["schemas"]["SpotSummary"];
            arrivalTime?: string;
            /** Format: int32 */
            durationMin?: number;
            travelMode?: string;
            /** Format: int32 */
            travelTimeMin?: number;
            memo?: string;
        };
        SpotSummary: {
            /** Format: uuid */
            id?: string;
            name?: string;
            category?: string;
            address?: string;
            lat?: number;
            lng?: number;
            thumbnailUrl?: string;
            collected?: boolean;
            visited?: boolean;
        };
        AddDayRequest: {
            /** Format: int32 */
            dayNumber: number;
            /** Format: date */
            date?: string;
        };
        ApiResponseItineraryDayResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ItineraryDayResponse"];
        };
        AddItemRequest: {
            /** Format: uuid */
            spotId: string;
            /** Format: int32 */
            orderIndex?: number;
            arrivalTime?: string;
            /** Format: int32 */
            durationMin?: number;
            travelMode?: string;
            /** Format: int32 */
            travelTimeMin?: number;
            memo?: string;
        };
        ApiResponseItineraryItemResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ItineraryItemResponse"];
        };
        CastVoteRequest: {
            votedPlan: string;
        };
        ApiResponseVoteStatusResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["VoteStatusResponse"];
        };
        VoteStatusResponse: {
            /** Format: uuid */
            sessionId?: string;
            status?: string;
            voteCounts?: {
                [key: string]: number;
            };
            /** Format: int32 */
            totalVotes?: number;
        };
        DayInput: {
            /** Format: int32 */
            day?: number;
            spotContentIds?: string[];
        };
        FinalizeItineraryRequest: {
            freePass: boolean;
            selectedPlan?: string;
            title: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            days?: components["schemas"]["DayInput"][];
            /** Format: uuid */
            requesterId?: string;
        };
        ApiResponseUUID: {
            success?: boolean;
            message?: string;
            /** Format: uuid */
            data?: string;
        };
        GroupItineraryRequest: {
            /** Format: date */
            startDate: string;
            startTime?: string;
            /** Format: date */
            endDate: string;
            endTime?: string;
            optimizationType?: string;
        };
        ApiResponseGroupItineraryGenerateResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GroupItineraryGenerateResponse"];
        };
        DayPlan: {
            /** Format: int32 */
            day?: number;
            spots?: components["schemas"]["SpotInfo"][];
            routes?: components["schemas"]["TransitRouteResponse"][];
        };
        GroupItineraryGenerateResponse: {
            /** Format: uuid */
            voteSessionId?: string;
            plans?: components["schemas"]["ItineraryGenerateResponse"];
        };
        ItineraryGenerateResponse: {
            planA?: components["schemas"]["PlanOption"];
            planB?: components["schemas"]["PlanOption"];
            planC?: components["schemas"]["PlanOption"];
        };
        PlanOption: {
            type?: string;
            label?: string;
            description?: string;
            days?: components["schemas"]["DayPlan"][];
        };
        SpotInfo: {
            contentId?: string;
            name?: string;
            category?: string;
            sigungu?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
            address?: string;
            thumbnailUrl?: string;
            operatingHours?: string;
        };
        SubPath: {
            type?: string;
            /** Format: int32 */
            sectionTime?: number;
            routeNo?: string;
            /** Format: int32 */
            stationCount?: number;
            startName?: string;
            endName?: string;
            /** Format: double */
            startX?: number;
            /** Format: double */
            startY?: number;
            /** Format: double */
            endX?: number;
            /** Format: double */
            endY?: number;
            startArsId?: string;
            /** Format: int32 */
            startId?: number;
            /** Format: int32 */
            wayCode?: number;
            /** Format: int32 */
            remainMinutes?: number;
        };
        TransitOption: {
            type?: string;
            /** Format: int32 */
            totalTime?: number;
            /** Format: int32 */
            totalFare?: number;
            /** Format: int32 */
            transferCount?: number;
            estimated?: boolean;
            subPaths?: components["schemas"]["SubPath"][];
        };
        TransitRouteResponse: {
            options?: components["schemas"]["TransitOption"][];
        };
        SwipeRequest: {
            swipes: components["schemas"]["SwipeItem"][];
            /** Format: date */
            startDate: string;
            startTime?: string;
            /** Format: date */
            endDate: string;
            endTime?: string;
            optimizationType?: string;
            /** Format: int32 */
            activityHours?: number;
        };
        ApiResponseItineraryGenerateResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ItineraryGenerateResponse"];
        };
        CreateGroupRequest: {
            name?: string;
        };
        ApiResponseGroupResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GroupResponse"];
        };
        GroupResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            inviteCode?: string;
            /** Format: uuid */
            createdBy?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        JoinGroupRequest: {
            inviteCode: string;
        };
        ApiResponseTokenResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TokenResponse"];
        };
        TokenResponse: {
            accessToken?: string;
            tokenType?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: unknown;
        };
        ApiResponseKakaoLoginResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["KakaoLoginResponse"];
        };
        KakaoLoginResponse: {
            accessToken?: string;
            tokenType?: string;
            isNewUser?: boolean;
        };
        MigrationResult: {
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            saved?: number;
            /** Format: int32 */
            updated?: number;
            /** Format: int32 */
            failed?: number;
        };
        UpdateProfileRequest: {
            nickname?: string;
            profileImageUrl?: string;
        };
        ApiResponseUserProfileResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["UserProfileResponse"];
        };
        UserProfileResponse: {
            /** Format: uuid */
            id?: string;
            nickname?: string;
            profileImageUrl?: string;
            email?: string;
        };
        UpdateLogRequest: {
            isPublic?: boolean;
            /** Format: int32 */
            mood?: number;
            theme?: string;
        };
        UpdateItemRequest: {
            /** Format: int32 */
            orderIndex?: number;
            arrivalTime?: string;
            /** Format: int32 */
            durationMin?: number;
            travelMode?: string;
            /** Format: int32 */
            travelTimeMin?: number;
            memo?: string;
        };
        UpdateItineraryRequest: {
            title?: string;
            /** Format: date */
            startAt?: string;
            startTime?: string;
            /** Format: date */
            endAt?: string;
            endTime?: string;
            status?: string;
        };
        ItineraryOptimizeRequest: {
            optimizationType?: string;
            startTime?: string;
        };
        ApiResponseItineraryOptimizeResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ItineraryOptimizeResponse"];
        };
        ItineraryOptimizeResponse: {
            spots?: components["schemas"]["OptimizedSpot"][];
            routes?: components["schemas"]["TransitRouteResponse"][];
            reason?: string;
        };
        OptimizedSpot: {
            contentId?: string;
            name?: string;
            /** Format: int32 */
            order?: number;
            arrivalTime?: string;
        };
        ApiResponseString: {
            success?: boolean;
            message?: string;
            data?: string;
        };
        ApiResponseListVisitHistoryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["VisitHistoryResponse"][];
        };
        VisitHistoryResponse: {
            /** Format: uuid */
            visitId?: string;
            /** Format: uuid */
            spotId?: string;
            spotName?: string;
            spotThumbnailUrl?: string;
            verified?: boolean;
            /** Format: double */
            distanceMeters?: number;
            /** Format: date-time */
            visitedAt?: string;
            photoUrls?: string[];
        };
        ApiResponseInteger: {
            success?: boolean;
            message?: string;
            /** Format: int32 */
            data?: number;
        };
        SpotDetailResponse: {
            spotId?: string;
            contentId?: string;
            name?: string;
            category?: string;
            address?: string;
            lat?: number;
            lng?: number;
            thumbnailUrl?: string;
            operatingHours?: string;
            overview?: string;
            tel?: string;
            homepage?: string;
            collected?: boolean;
            visited?: boolean;
        };
        SpotSearchResponse: {
            /** Format: uuid */
            spotId?: string;
            contentId?: string;
            name?: string;
            category?: string;
            /** Format: int32 */
            sigunguId?: number;
            sigunguName?: string;
            address?: string;
            thumbnailUrl?: string;
            isCollection?: boolean;
            collected?: boolean;
            visited?: boolean;
        };
        ApiResponseListTravelLogSummaryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TravelLogSummaryResponse"][];
        };
        TravelLogSummaryResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            thumbnailPhotoUrl?: string;
            isPublic?: boolean;
            /** Format: date */
            startDate?: string;
            /** Format: int32 */
            totalSpots?: number;
            /** Format: int32 */
            collectedSpots?: number;
            authorNickname?: string;
            /** Format: int32 */
            addedCount?: number;
            /** Format: int32 */
            mood?: number;
            theme?: string;
            /** Format: int32 */
            travelNumber?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiResponseListItinerarySummaryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ItinerarySummaryResponse"][];
        };
        ItinerarySummaryResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            planType?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseListGroupMemberResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GroupMemberResponse"][];
        };
        ApiResponseListGroupResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["GroupResponse"][];
        };
        CollectionListResponse: {
            /** Format: uuid */
            spotId?: string;
            name?: string;
            /** Format: int32 */
            sigunguId?: number;
            thumbnailUrl?: string;
            collected?: boolean;
            /** Format: date-time */
            collectedAt?: string;
        };
        CollectionDetailResponse: {
            /** Format: uuid */
            spotId?: string;
            collected?: boolean;
            /** Format: date-time */
            collectedAt?: string;
        };
        BookmarkListResponse: {
            /** Format: uuid */
            spotId?: string;
            name?: string;
            category?: string;
            /** Format: int32 */
            sigunguId?: number;
            thumbnailUrl?: string;
            /** Format: date-time */
            bookmarkedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListVisitHistoryResponse"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVisitResponse"];
                };
            };
        };
    };
    attachPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                visitId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachVisitPhotoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVisitPhotoResponse"];
                };
            };
        };
    };
    presign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignUploadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePresignUploadResponse"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwipeSubmitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSwipeSessionResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLogRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogDetailResponse"];
                };
            };
        };
    };
    addPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPhotoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogPhotoResponse"];
                };
            };
        };
    };
    addHashtag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddHashtagRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogHashtagResponse"];
                };
            };
        };
    };
    getList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListItinerarySummaryResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItineraryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryDetailResponse"];
                };
            };
        };
    };
    addDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDayRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryDayResponse"];
                };
            };
        };
    };
    addItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: string;
                dayId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryItemResponse"];
                };
            };
        };
    };
    castVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CastVoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoteStatusResponse"];
                };
            };
        };
    };
    finalize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeItineraryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUUID"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupItineraryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupItineraryGenerateResponse"];
                };
            };
        };
    };
    generateItinerary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwipeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryGenerateResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupResponse"];
                };
            };
        };
    };
    join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGroupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupResponse"];
                };
            };
        };
    };
    addBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeBookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    kakaoLogin: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseKakaoLoginResponse"];
                };
            };
        };
    };
    run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MigrationResult"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserProfileResponse"];
                };
            };
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserProfileResponse"];
                };
            };
        };
    };
    setRepresentative: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logId: string;
                itemId: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogPhotoResponse"];
                };
            };
        };
    };
    getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogDetailResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLogRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseTravelLogDetailResponse"];
                };
            };
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: string;
                dayId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: string;
                dayId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryItemResponse"];
                };
            };
        };
    };
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryDetailResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItineraryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryDetailResponse"];
                };
            };
        };
    };
    optimize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dayId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryOptimizeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseItineraryOptimizeResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseString"];
                };
            };
        };
    };
    getBusArrival: {
        parameters: {
            query: {
                arsId: string;
                routeNo: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseInteger"];
                };
            };
        };
    };
    getDetail_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SpotDetailResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                keyword?: string;
                sigunguId?: number;
                category?: string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SpotSearchResponse"][];
                };
            };
        };
    };
    getLogsBySpot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelLogSummaryResponse"];
                };
            };
        };
    };
    getPublicLogs: {
        parameters: {
            query?: {
                category?: string;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelLogSummaryResponse"];
                };
            };
        };
    };
    getMyLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTravelLogSummaryResponse"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoteStatusResponse"];
                };
            };
        };
    };
    members: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListGroupMemberResponse"];
                };
            };
        };
    };
    myGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListGroupResponse"];
                };
            };
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectionListResponse"][];
                };
            };
        };
    };
    getDetail_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CollectionDetailResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSwipeDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SpotSearchResponse"][];
                };
            };
        };
    };
    getBookmarks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BookmarkListResponse"][];
                };
            };
        };
    };
    deletePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logId: string;
                itemId: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteHashtag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                logId: string;
                itemId: string;
                hashtagId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itineraryId: string;
                dayId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
